### ISSUE TITLE
Main.c file - Too many arguments

### ISSUE THREAD

**Issue by mharris-t** [stevenblair/rapid61850#7]
I am trying to run the main.c file to simulate the IEDs from the scd.xml file provided in your repository. I have been getting the following error:

![image](https://user-images.githubusercontent.com/60294955/83756959-76583500-a678-11ea-9416-b2be6a0b9efd.png)

Is there any solution for this? Thanks!

**Comment by stevenblair** [comment]
This should be fixed now, by removing the third argument. Not sure how that hasn't come up before! Thanks.

**Comment by mharris-t** [comment]
Thank you very much for your prompt reply. I have made changes to the file as you have described in your commit. However, I am getting the following error: 

![image](https://user-images.githubusercontent.com/60294955/83857172-4023bf80-a723-11ea-8eb6-58d8298508dc.png)

Also, if I want to simulate custom IEDs, do I need to call them in this line :  **int charsPrinted =  itemTreeToJSON(printBuf, getIED("LE_IED"))** ?

**Comment by mharris-t** [comment]
Thank you very much for your prompt reply. I have made changes as you have described in your commit. Also, I am trying to simulate a custom IED with the name LE_IED. After generating the C code, variables which are associated to E1Q1SB1 IED from your scd.xml file are still present. Should I change them as well? Or should I be running another C file to simulate my IED? I am a bit confused regarding this. Thanks.

**Comment by mharris-t** [comment]
I am getting errors like this one when I try to run main.c file: 

![image](https://user-images.githubusercontent.com/60294955/83882108-4da07000-a74a-11ea-8eac-d003afa52722.png)

**Comment by mharris-t** [comment]
I have changed the variables appropriately based on how the IEDs are defined in ied.h file. I can run the C code now. Thanks.
